name: Discord ä¸»é¡ŒåŒ…æ›´æ–°é€šçŸ¥

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_ID }}
          webhook_token: ${{ secrets.DISCORD_TOKEN }}
          username: "Discord ä¸»é¡ŒåŒ…æ›´æ–°é€šçŸ¥"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          message: |
            ## ğŸš€ æ–°ç‰ˆæœ¬ç™¼ä½ˆï¼š${{ github.event.release.name }}
            **ç‰ˆæœ¬è™Ÿç¢¼:** `${{ github.event.release.tag_name }}`
            **ç™¼ä½ˆè€…:** <@630687657885827103>
            
            ${{ github.event.release.body }}
            
            [ğŸ“¦ é»æ­¤å‰å¾€ä¸‹è¼‰ä¸»é¡ŒåŒ…](${{ github.event.release.html_url }})